# Generated by Django 5.1 on 2024-10-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_backupsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsettings',
            name='backup_date',
            field=models.CharField(max_length=100),
        ),
    ]
