# Generated by Django 5.1 on 2024-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_backupsettings_backup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='confirm_backup',
            field=models.BooleanField(default=False),
        ),
    ]
